sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t yjk9805/docker-react-app -f Dockerfile.dev .
  
script:
  - docker run -e CI=true yjk9805/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test succes"